### ISSUE TITLE
[Request] 在结果部分展示 Markdown 解析后的图片

### ISSUE THREAD

**Issue by arvinxx** [mushan0x0/lobe-pollinations-ai#1]
### 🥰 需求描述 | Feature Description

建议在结果部分展示 Markdown 解析后的图片：

<img width="912" alt="image" src="https://github.com/mushan0x0/lobe-pollinations-ai/assets/28616219/d4247c18-fec0-4ace-9845-08b4061c1a3c">

### 🧐 解决方案 | Proposed Solution

可以使用 Lobe UI  的 Markdown 组件： https://ui.lobehub.com/components/markdown

**Comment by mushan0x0** [comment]
我试了的，因为插件界面是 iframe，弹出层不能覆盖的外面界面，加上下面 gpt 会回复一个图片，所以只展示参数就行了
<img width="950" alt="image" src="https://github.com/mushan0x0/lobe-pollinations-ai/assets/29084441/c47f4518-5af4-47fa-a783-716eb0ba951e">

**Comment by arvinxx** [comment]
那我建议直接回复一个链接吧。这样用户可以点这个链接去新开页面看大图？

**Comment by mushan0x0** [comment]
不过界面上可以把这个删掉，因为链接很长，又是没有渲染的 md 语法
<img width="718" alt="image" src="https://github.com/mushan0x0/lobe-pollinations-ai/assets/29084441/84b560bd-47d5-4abc-8359-0d66413ddf3c">

**Comment by mushan0x0** [comment]
具体返回然后看 debug 信息就行了

**Comment by arvinxx** [comment]
考虑下换成新的 markdown 类型插件？感觉上面的问题在md 插件下都迎刃而解了

https://github.com/lobehub/lobe-chat/pull/865

**Comment by mushan0x0** [comment]
> 考虑下换成新的 markdown 类型插件？感觉上面的问题在md 插件下都迎刃而解了
> 
> [lobehub/lobe-chat#865](https://github.com/lobehub/lobe-chat/pull/865)

这个不错👍
